name: "worfklow_dispatch"
on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username"
        required: true
        type: string
      level:
        description: "Level"
        required: true
        type: string
      class:
        description: "Class"
        required: true
        type: choice
        options:
          - "jedi"
          - "sith"
          - "rebel"
jobs:
  player_infos:
    runs-on: ubuntu-latest
    steps:
    - name: "Display Player Infos"
      run: echo "Le Joueur ${{ inputs.username }} est de niveau ${{ inputs.level }} et joue un ${{ inputs.class }}."
